#!/usr/bin/env python3
"""
Visualize SLAM pose logs (generated by slam_rgb_demo.py) with rerun.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import List, Tuple

import numpy as np


def _import_rerun():
    try:
        import rerun as rr  # type: ignore
    except Exception as exc:  # pragma: no cover - optional dependency
        raise RuntimeError("rerun is required: pip install rerun-sdk") from exc
    return rr


def load_valid_samples(csv_path: Path) -> Tuple[np.ndarray, np.ndarray]:
    """
    Load pose samples from the CSV, discarding entries with invalid timestamps or confidence.

    Returns:
        times: (N,) array of host timestamps in seconds.
        positions: (N, 3) array of XYZ positions in meters.
    """
    times: List[float] = []
    positions: List[List[float]] = []

    with csv_path.open("r", newline="") as csvfile:
        reader = csv.DictReader(csvfile)
        required = [
            "host_timestamp",
            "confidence",
            "pos_x",
            "pos_y",
            "pos_z",
        ]
        missing = set(required) - set(reader.fieldnames or [])
        if missing:
            raise ValueError(f"{csv_path} missing columns: {', '.join(sorted(missing))}")

        for row in reader:
            try:
                host_ts = float(row["host_timestamp"])
                confidence = float(row["confidence"])
                pos = [float(row["pos_x"]), float(row["pos_y"]), float(row["pos_z"])]
            except ValueError:
                print(f"Skip malformed row: {row}")
                continue

            if host_ts <= 0 or confidence <= 0:
                continue
            times.append(host_ts)
            positions.append(pos)

    if not times:
        raise ValueError(f"No valid samples found in {csv_path}.")

    times_arr = np.asarray(times, dtype=np.float64)
    positions_arr = np.asarray(positions, dtype=np.float32)
    return times_arr, positions_arr


def visualize(csv_path: Path, spawn: bool) -> None:
    times, positions = load_valid_samples(csv_path)

    rr = _import_rerun()
    rr.init(f"XVisio SLAM Trajectory ({csv_path.name})", spawn=spawn)
    try:
        rr.log("world", rr.ViewCoordinates.RDF)
    except Exception:
        pass

    # Draw the entire path as a line strip for global context.
    rr.log(
        "slam/trajectory/full",
        rr.LineStrips3D(
            [positions],
            colors=np.array([[0, 200, 255, 255]], dtype=np.uint8),
            radii=np.full(1, 0.01, dtype=np.float32),
        ),
    )
    rr.log(
        "slam/trajectory/points",
        rr.Points3D(
            positions,
            colors=np.array([[255, 255, 255, 255]], dtype=np.uint8),
            radii=np.full(len(positions), 0.008, dtype=np.float32),
        ),
    )

    # Animate the camera position over time.
    for ts, pos in zip(times, positions):
        rr.set_time_seconds("host_time", ts)
        rr.log(
            "slam/trajectory/camera_pose",
            rr.Transform3D(translation=pos),
        )
        rr.log(
            "slam/trajectory/current",
            rr.Points3D(
                pos[None, :],
                colors=np.array([[255, 120, 0, 255]], dtype=np.uint8),
                radii=np.full(1, 0.015, dtype=np.float32),
            ),
        )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Visualize slam_rgb_demo pose logs with rerun."
    )
    parser.add_argument(
        "log_csv",
        type=Path,
        help="Path to the CSV file generated by slam_rgb_demo.py",
    )
    parser.add_argument(
        "--spawn",
        action="store_true",
        help="Spawn a separate Rerun Viewer window.",
    )
    args = parser.parse_args()

    visualize(args.log_csv, spawn=args.spawn)


if __name__ == "__main__":
    main()
