inherit_from: ./configs/wildgs_slam.yaml

scene: slam_glass_demo

dataset: 'glass'

data:
  input_folder: ./data/20251112_142342
  output: ./data/20251112_142342

cam:
  H: 360
  W: 640
  H_out: 360
  W_out: 640
  fx: 194.3180
  fy: 194.3455
  cx: 163.5895
  cy: 91.0140

mapping:
  Training:
    alpha: 0.8
  uncertainty_params:
    uncer_depth_mult: 0.2
